openapi: 3.0.0
info:
  title: Data Agreement Audit API
  description: Proposed Audit API for a Verifier to offer Data Agreement auditing capabilities. Intended for interop testing. Not needed to implement to conform to VUI
  version: 1.0.0
servers:
  - url: https://vui.gataca.io/api/v1
    description: Gataca's implementor server
  - url: http://data-agreements.igrant.io/api/v1
    description: IGrantio Data Agreements Server

paths:
  /health:
    get:
      summary: Returns if the service is up and running.
      description: Optional extended description in CommonMark or HTML.
      tags:
        - Integration
      responses:
        '200':    # status code
          description: Server UP
  /version:
    get:
      summary: Returns the current version of the service.
      description: Optional extended description in CommonMark or HTML.
      tags:
        - Integration
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: object
                properties:
                  version:
                    type: string
                  releaseDate:
                    type: string
                    format: date    

components:
  schemas:
    data_agreement: 
      type: object
    data_agreement_offer: 
      type: object
    data_agreement_acceptance: 
      type: object
    data_agreement_declination: 
      type: object
      
  securitySchemes:
    ApiKeyAuth:       
      type: apiKey
      in: header       # can be "header", "query" or "cookie"
      name: X-API-KEY  # name of the header, query parameter or cookie
    basicAuth:    
      type: http
      scheme: basic
    bearerAuth:      
      type: http
      scheme: bearer
      bearerFormat: JWT 